export const imageData = [
    {
        image:'images/img1.jpg'
    },
    {
        image:'images/img2.jpg'
    },
    {
        image:'images/img3.jpg'
    },
    {
        image:'images/img4.jpg'
    },
    {
        image:'images/img5.jpg'
    },
    {
        image:'images/img6.jpg'
    },
    {
        image:'images/img7.jpg'
    },    
    {
        image:'images/img8.jpg'
    },
    {
        image:'images/slide_3.jpg'
    },

]